[package]
name = "rchess_uci"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rchess_engine = { path = "../rchess_engine" }

rayon = "1.5.1"

log = "0.4.*"
env_logger = "0.9.*"
gag = "1.0.0"

