[workspace]

members = [
    "rchess_uci",
    "rchess_engine",
    # "rchess_magics",
]
# exclude = [
#     "rchess_game",
# ]


[profile.dev.package."*"]
opt-level = 3

[profile.release]
debug = 1

