[package]
name = "rchess_engine"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rchess_engine_lib"
path = "src/lib.rs"

[[bin]]
name = "rchess_engine"
path = "src/main.rs"

[dependencies]

log = "0.4.*"
env_logger = "0.9.*"
gag = "1.0.0"

nom = "7.0.0"

bitflags = "1.3"

# byteorder = "1.4.3"

