[package]
name = "rchess_tuner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "rchess_tuner_lib"
path = "src/lib.rs"

[[bin]]
name = "rchess_tuner"
path = "src/main.rs"

[dependencies]
